version: '3.8'


services:
 backend:
  image: awalaa220/backend
  container_name: backend-service
  ports:
    - "30009:3001"
  environment:
    - NODE_ENV=development
    - PORT=3001
  
  restart:
    always
  
    
 frontend:
   image: awalaa220/frontend
   container_name: frontend-service
   ports:
     - "30008:3000"
   restart: always
   depends_on: 
     - backend
