version: '3.8'


services:
 backend:
  build:
   context: ./backend
  container_name: backend-service
  ports:
    - "5000:5000"
  environment:
    - NODE_ENV=development
  volumes:
    - ./backend:/app
  restart: always
 
 frontend:
   build:
     context: ./frontend
   container_name: frontend-service
   ports:
     - "3000:3000"
   environment:
     - REACT_APP_API_URL=http://backend:5000
     - BROWSER=none
   volumes:
     - ./frontend:/app
   depends_on:
     - backend
   restart: always

