version: '3.8'


services:
 backend:
  build:
   context: ./backend
  container_name: backend-service
  ports:
    - "3001:3001"
  environment:
    - NODE_ENV=development
  volumes:
    - ./backend:/app
    - /var/run/docker.sock:/var/run/docker.sock
  network_mode: "host"

 
 frontend:
   build:
     context: ./frontend
   container_name: frontend-service
   ports:
     - "3000:3000"
   environment:
     - REACT_APP_API_URL=http://backend:5000
     - BROWSER=none
   volumes:
     - ./frontend:/app
     - /var/run/docker.sock:/var/run/docker.sock
   depends_on:
     - backend
   network_mode: "host"


