apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend

spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: frontend
        image: awalaa220/frontend
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - port: 3000

      targetPort: 3000

      nodePort: 30008
